name: 🚀 Feature Request
description: Suggest an idea for the plugin
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - felixgeelhaar

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible about your idea.

  - type: checkboxes
    id: search
    attributes:
      label: Search for existing requests
      description: Please search for existing feature requests before creating a new one
      options:
        - label: I have searched for existing feature requests and this is not a duplicate
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature request fall into?
      options:
        - Light Control (individual lights)
        - Group Management (light groups)
        - User Interface (Property Inspector)
        - Stream Deck Integration
        - Govee API Integration
        - Performance/Optimization
        - Accessibility
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Essential for my use case
        - Critical - Blocking my usage of the plugin
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor UI change or configuration option
        - Medium - New functionality within existing framework
        - Complex - Major new feature requiring significant changes
        - Unknown - I'm not sure about the technical complexity

  - type: checkboxes
    id: help
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to contribute code for this feature
        - label: I would be willing to help with testing
        - label: I would be willing to help with documentation
        - label: I would be willing to provide feedback during development

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        Example:
        - I have 20+ Govee lights in different rooms
        - I want to create scene-based lighting for different activities
        - This would help me quickly switch between work/entertainment modes

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If you have any mockups, wireframes, or reference screenshots, please share them
      placeholder: Drag and drop images here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request here
      placeholder: Any additional information that might be helpful...